name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploying NodeJS Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit testing
        run: npm i && npm run test

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
          
      - name: deploying application to EC2
        env:
          HOSTNAME: ${{ secrets.SERVER_HOST }}
          USER_NAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}

        run: |
          ssh -o StrictHostKeyChecking=no -p ${PORT} ${USER_NAME}@${HOSTNAME} bash auto-deploy.sh
